apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      name: "goserver"
      labels:
        app: "goserver"
    spec:
      containers:
      - name: goserver
        image: "matheushenrique35/helloworldgo:v6"
        env: 
          - name: NAME
            value: "Matheus"
          - name: AGE
            value: "21"