apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver # nome do pods do deployment
  replicas: 2
  template:
    metadata:
      name: "goserver"
      labels:
        app: "goserver"
    spec:
      containers:
      - name: goserver
        image: matheushenrique35/helloworldgo:v8.4
        readinessProbe: # config para aguardar meu container estiver pronto para enviar trafego de rede
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 3
          failureThreshold: 1
          initialDelaySeconds: 10

        envFrom:
          - configMapRef:
              name: goserver-enviroment # mapeia automaticamente os as chaves existentes no arquivo de configuracao
        volumeMounts:
          - mountPath: /go/myfamily
            name: config
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
            - key: members
              path: family.txt