apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver # nome do pods do deployment
  replicas: 2
  template:
    metadata:
      name: "goserver"
      labels:
        app: "goserver"
    spec:
      containers:
      - name: goserver
        image: matheushenrique35/helloworldgo:v8.4

        resources:
          requests: # o minimo que uma aplicação precisa, e automaticamente esses recursos e alocado no POD.
            cpu: 10m
            memory: 20Mi
          limits: # limite de recursos que cada pod pode alocar
            cpu: 20m # evitar que a soma de pods criados ultrapasse o valor total de recurso de CPU disponivel
            memory: 25Mi

        readinessProbe: # faz exatamente a mesma coisa que o livennes, porém em caso de erro ele não faz o envio de trafego de rede, quando a verificação der sucesso, começa a enviar trafego.
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 3
          failureThreshold: 1
          initialDelaySeconds: 10 # configura um delay para iniciar as verificações do readiness, enquanto isso o container não fica disponivel. 

        envFrom:
          - configMapRef:
              name: goserver-enviroment # mapeia automaticamente os as chaves existentes no arquivo de configuracao
        volumeMounts:
          - mountPath: /go/myfamily
            name: config
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
            - key: members
              path: family.txt