apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver # nome do pods do deployment
  replicas: 1
  template:
    metadata:
      name: "goserver"
      labels:
        app: "goserver"
    spec:
      containers:
      - name: goserver
        image: matheushenrique35/helloworldgo:v8.4
        
        resources:
          requests: # o minimo que uma aplicação precisa, e automaticamente esses recursos e alocado no POD.
            cpu: 10m
            memory: 20Mi
          limits: # limite de recursos que cada pod pode alocar
            cpu: 20m # evitar que a soma de pods criados ultrapasse o valor total de recurso de CPU disponivel
            memory: 25Mi

        envFrom:
          - configMapRef:
              name: goserver-enviroment # mapeia automaticamente os as chaves existentes no arquivo de configuracao
        volumeMounts:
          - mountPath: /go/myfamily
            name: config
            readOnly: true
          - mountPath: "/go/pvc"
            name: goserver-volume
            
        # env: 
        #   - name: NAME
        #     valueFrom:
        #       configMapKeyRef:
        #         name: goserver-env
        #         key: name
          # - name: AGE
          #   value: '88'

      volumes:
        - name: goserver-volume
          persistentVolumeClaim:
            claimName: goserver-pvc
        - name: config
          configMap:
            name: configmap-family
            items:
            - key: members
              path: family.txt