apiVersion: v1
kind: Service
metadata:
  name: goserver-service # nome do meu service
spec:
  selector:
    app: goserver # e responsavel por filtrar todos os pods que estão incorporado nesse servico
#  type: LoadBalancer
  type: ClusterIP
#  type: NodePort
  ports:
    - name: goserver-portservice
      port: 80 # porta do service
      targetPort: 8000 # porta do container que e exportada na aplicacao-imagem
      protocol: TCP