apiVersion: v1
kind: Pod
metadata:
  name: nginxpodname
  labels:
    name: nginxpod # deixa o pod selecionavel
spec:
  containers:
  - name: nginxcontainer
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
